### ISSUE TITLE
opencv文档2019年07月11日22:59:14校对

### ISSUE THREAD

**Issue by jerryqiang** [apachecn/opencv-doc-zh#34]
3.2和4.1等图片失效：/docs/4.0.0/img/function/ 图片文件缺失。
官网教程2.2 保存视频示例代码运行有问题，建议替换。
此外有个不成熟的小建议，我们可以给练习添加下参考代码
暂时只看到这些。

**Comment by wizardforcel** [comment]
请直接提 pull request 谢谢
