### ISSUE TITLE
页面图片显示不正常

### ISSUE THREAD

**Issue by SChen1024** [apachecn/opencv-doc-zh#43]
# 第四章的图片链接普遍存在问题,  可见下图链接,还请 复查一下
## 界面显示图片不显示问题
图像找不到链接, 
![image](https://user-images.githubusercontent.com/12789460/65236518-5c3aee80-db0b-11e9-9a4b-2f6672fc2acf.png)

## 界面部分链接不到图片 
如图所示, 在页面[图像阈值](https://opencv.apachecn.org/#/docs/4.0.0/4.3-tutorial_py_thresholding) 页面存在图片链接,但是文件夹内找不到相应的图片的问题
![image](https://user-images.githubusercontent.com/12789460/65236771-d8353680-db0b-11e9-8e6e-9c53519d27b9.png)

**Comment by daidai21** [comment]
看到了, 稍后处理

**Comment by daidai21** [comment]
@jiangzhonglian 老哥，我merge了，但是貌似要你重新生成下这个静态网页

**Comment by SChen1024** [comment]
在线阅读的站点中 [图片梯度](https://opencv.apachecn.org/#/docs/4.0.0/4.7)  1.7章节- 4.16 章节 都无法访问 
应该是目录和文件名没有对应上, 可能是文件名改了, 但是链接没有更新
![image](https://user-images.githubusercontent.com/12789460/65245291-e771af80-db1e-11e9-8593-826114d7f82d.png)

**Comment by jiangzhonglian** [comment]
这个是自动生成页面，不需要人在干预，😂哈哈哈 

我看到你们修改好了，现在页面正常显示

![image](https://user-images.githubusercontent.com/9199175/65295702-c6e43c80-db94-11e9-95f2-2319f537359e.png)

**Comment by wizardforcel** [comment]
还有其他不正常的地方嘛？

**Comment by SChen1024** [comment]
已经提了 PR  
部分章节没有加入 4.9 4.10 4.11  都有子内容没有添加 之后提PR 修复
