### ISSUE TITLE
轮廓的轮廓层次部分内容有误

### ISSUE THREAD

**Issue by lsh1994** [apachecn/opencv-doc-zh#55]
![image](https://user-images.githubusercontent.com/14355014/103392237-d3a55d80-4b57-11eb-9c39-29ddc5435554.png)
![image](https://user-images.githubusercontent.com/14355014/103392248-def88900-4b57-11eb-95a2-001deff2a9ca.png)

**Comment by jiangzhonglian** [comment]
方便提交一个PR吗？
